# Site settings
title: Lo√Øc Fejoz - F4JXQ
email: loic@fejoz.net
description: "Est sempter altera via melior"
baseurl: ""
url: "https://www.fejoz.net"
github_username:  loic-fejoz

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments